import os
import django
from decimal import Decimal

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "config.settings")
django.setup()

from store.models import Product
from catalog.models import Category

def get_cat(slug, default_slug="grocery-kirana"):
    cat = Category.objects.filter(slug=slug).first()
    if not cat:
        cat = Category.objects.filter(slug=default_slug).first()
    return cat

products_data = [
    {
        "id": 1,
        "name": "Tata Salt Vacuum Evaporated Iodised Salt",
        "cat_slug": "sugar-salt",
        "description": "Tata Salt has vacuum evaporated purity with guaranteed iodine content for everyday wholesome family health. Desh Ka Namak!",
        "price": Decimal("30.00"),
        "discount": Decimal("6.67"),
        "stock": Decimal("200.00"),
        "unit": "kg",
        "weight": "1 kg Pack",
        "brand": "Tata Salt",
        "image": "products/salt.jpg",
    },
    {
        "id": 2,
        "name": "Aashirvaad Shudh Chakki Whole Wheat Atta",
        "cat_slug": "atta-flour",
        "description": "100% pure whole wheat stone-ground chakki flour that locks in nutrients and fiber for soft, fluffy rotis every time.",
        "price": Decimal("295.00"),
        "discount": Decimal("10.17"),
        "stock": Decimal("120.00"),
        "unit": "kg",
        "weight": "5 kg Bag",
        "brand": "Aashirvaad",
        "image": "products/atta.jpg",
    },
    {
        "id": 3,
        "name": "Fortune Sunlite Refined Sunflower Oil",
        "cat_slug": "oil-ghee",
        "description": "Light and healthy cooking oil enriched with vitamins A & D, ideal for all everyday Indian cooking and frying.",
        "price": Decimal("155.00"),
        "discount": Decimal("10.97"),
        "stock": Decimal("95.00"),
        "unit": "litre",
        "weight": "1 Litre Pouch",
        "brand": "Fortune",
        "image": "products/oil.jpg",
    },
    {
        "id": 4,
        "name": "India Gate Basmati Rice Feast Rozzana",
        "cat_slug": "rice-grains",
        "description": "Premium aged long-grain basmati rice with exquisite aroma and distinct fluffy grains, perfect for daily pulao and biryani.",
        "price": Decimal("450.00"),
        "discount": Decimal("13.56"),
        "stock": Decimal("80.00"),
        "unit": "kg",
        "weight": "5 kg Bag",
        "brand": "India Gate",
        "image": "products/rice.jpg",
    },
    {
        "id": 5,
        "name": "Tata Sampann Unpolished Toor Dal",
        "cat_slug": "dal-pulses",
        "description": "Natural, unpolished pigeon pea lentils rich in wholesome plant protein without water or oil polishing.",
        "price": Decimal("185.00"),
        "discount": Decimal("9.19"),
        "stock": Decimal("90.00"),
        "unit": "kg",
        "weight": "1 kg Pack",
        "brand": "Tata Sampann",
        "image": "products/toor_dal.jpg",
    },
    {
        "id": 6,
        "name": "Everest Garam Masala Pure Spices",
        "cat_slug": "spices-masala",
        "description": "A well-balanced blend of 13 aromatic whole spices ground to perfection for authentic Indian curries and sabzis.",
        "price": Decimal("88.00"),
        "discount": Decimal("11.36"),
        "stock": Decimal("150.00"),
        "unit": "pack",
        "weight": "100 g Box",
        "brand": "Everest",
        "image": "products/masala.jpg",
    },
    {
        "id": 7,
        "name": "Amul Taaza Fresh Homogenised Toned Milk",
        "cat_slug": "milk",
        "description": "Fresh, pasteurised toned milk fortified with vitamins A and D. Wholesome nutrition for the entire family.",
        "price": Decimal("28.00"),
        "discount": Decimal("3.57"),
        "stock": Decimal("120.00"),
        "unit": "pouch",
        "weight": "500 ml Pouch",
        "brand": "Amul",
        "image": "products/milk.jpg",
    },
    {
        "id": 8,
        "name": "Amul Fresh Malai Paneer Block",
        "cat_slug": "paneer",
        "description": "Soft, creamy cottage cheese made from pure milk, ready to cut and cook in your favourite shahi paneer or tikka.",
        "price": Decimal("95.00"),
        "discount": Decimal("5.26"),
        "stock": Decimal("60.00"),
        "unit": "pack",
        "weight": "200 g Pack",
        "brand": "Amul",
        "image": "products/paneer.jpg",
    },
    {
        "id": 9,
        "name": "Mother Dairy Classic Dahi Cup",
        "cat_slug": "curd",
        "description": "Traditional thick, creamy and rich set dahi made with wholesome milk cultures. Great with parathas and raita.",
        "price": Decimal("35.00"),
        "discount": Decimal("0.00"),
        "stock": Decimal("80.00"),
        "unit": "cup",
        "weight": "400 g Tub",
        "brand": "Mother Dairy",
        "image": "products/curd.jpg",
    },
    {
        "id": 10,
        "name": "Amul Pasteurized Table Butter",
        "cat_slug": "butter",
        "description": "The classic utterly butterly delicious salted table butter, essential for morning breakfast toasts and parathas.",
        "price": Decimal("58.00"),
        "discount": Decimal("3.45"),
        "stock": Decimal("110.00"),
        "unit": "pack",
        "weight": "100 g Carton",
        "brand": "Amul",
        "image": "products/butter.jpg",
    },
    {
        "id": 11,
        "name": "Fresh Desi Farm Hybrid Tomatoes",
        "cat_slug": "vegetables",
        "description": "Crisp, plump and juicy farm-fresh red desi tomatoes, rich in vitamin C and perfect for daily curries and salads.",
        "price": Decimal("45.00"),
        "discount": Decimal("22.22"),
        "stock": Decimal("180.00"),
        "unit": "kg",
        "weight": "1 kg",
        "brand": "Apna Farm",
        "image": "products/tomatoes.jpg",
    },
    {
        "id": 12,
        "name": "Fresh Green Shimla Capsicum",
        "cat_slug": "vegetables",
        "description": "Crisp and thick-walled shiny green bell peppers, freshly harvested and perfect for stir-fries and pizza toppings.",
        "price": Decimal("55.00"),
        "discount": Decimal("18.18"),
        "stock": Decimal("90.00"),
        "unit": "kg",
        "weight": "500 g",
        "brand": "Apna Farm",
        "image": "products/capsicum.jpg",
    },
    {
        "id": 13,
        "name": "Fresh Palak (Green Spinach Leaves)",
        "cat_slug": "leafy-vegetables",
        "description": "Tender, green, dirt-free farm spinach leaves packed with natural iron and minerals for healthy dal palak or palak paneer.",
        "price": Decimal("25.00"),
        "discount": Decimal("20.00"),
        "stock": Decimal("100.00"),
        "unit": "bunch",
        "weight": "250 g Bunch",
        "brand": "Apna Farm",
        "image": "products/palak.jpg",
    },
    {
        "id": 14,
        "name": "Shimla Royal Delicious Red Apples",
        "cat_slug": "fresh-fruits",
        "description": "Handpicked sweet, crunchy red delicious apples from the high-altitude orchards of Himachal Pradesh.",
        "price": Decimal("180.00"),
        "discount": Decimal("13.89"),
        "stock": Decimal("70.00"),
        "unit": "kg",
        "weight": "1 kg (approx 4-5 pcs)",
        "brand": "Himachal Fresh",
        "image": "products/apples.jpg",
    },
    {
        "id": 15,
        "name": "Fresh Robusta Bananas (1 Dozen)",
        "cat_slug": "fresh-fruits",
        "description": "Naturally ripened sweet and energetic Robusta bananas, harvested fresh from southern farm groves.",
        "price": Decimal("60.00"),
        "discount": Decimal("20.00"),
        "stock": Decimal("95.00"),
        "unit": "dozen",
        "weight": "12 pcs (1 Dozen)",
        "brand": "Apna Farm",
        "image": "products/bananas.jpg",
    },
    {
        "id": 16,
        "name": "Handcrafted Clay Water Matka with Brass Tap",
        "cat_slug": "matka",
        "description": "Eco-friendly natural terracotta earthenware water pot with sturdy jute coaster and fitted brass tap for naturally cool water.",
        "price": Decimal("399.00"),
        "discount": Decimal("25.06"),
        "stock": Decimal("40.00"),
        "unit": "piece",
        "weight": "10 Litre Capacity",
        "brand": "Desi Shilpkar",
        "image": "products/matka.jpg",
    },
    {
        "id": 17,
        "name": "Traditional Desi Mitti Kulhad Chai Cups (Set of 6)",
        "cat_slug": "kulhad",
        "description": "Authentic unglazed terracotta clay tea cups made by village potters. Imparts unmatched earthy aroma (saundhi khushboo) to chai.",
        "price": Decimal("140.00"),
        "discount": Decimal("29.29"),
        "stock": Decimal("85.00"),
        "unit": "set",
        "weight": "Pack of 6 Cups (150ml each)",
        "brand": "Desi Shilpkar",
        "image": "products/kulhad.jpg",
    },
    {
        "id": 18,
        "name": "Terracotta Akhand Diya with Rangoli Pattern (Set of 4)",
        "cat_slug": "diya",
        "description": "Hand-molded earthenware oil lamps with deep oil wells, crafted for auspicious Diwali, Navratri and daily puja ceremonies.",
        "price": Decimal("160.00"),
        "discount": Decimal("25.00"),
        "stock": Decimal("130.00"),
        "unit": "set",
        "weight": "Pack of 4 Diyas",
        "brand": "Desi Shilpkar",
        "image": "products/diya.jpg",
    },
    {
        "id": 19,
        "name": "Mangaldeep Temple Gold Agarbatti (100 Sticks)",
        "cat_slug": "agarbatti-dhoop",
        "description": "High fragrance devotional incense sticks blended with pure floral extracts and sacred sandalwood oils for serene prayers.",
        "price": Decimal("75.00"),
        "discount": Decimal("13.33"),
        "stock": Decimal("160.00"),
        "unit": "pack",
        "weight": "Pack of 100 Sticks",
        "brand": "Mangaldeep",
        "image": "products/agarbatti.jpg",
    },
    {
        "id": 20,
        "name": "Traditional Hindu Puja Thali Decorated Set (7 Pieces)",
        "cat_slug": "puja-thali",
        "description": "Gleaming brass ritual thali complete with oil diya lamp, incense holder, small bell, and auspicious kumkum bowls.",
        "price": Decimal("699.00"),
        "discount": Decimal("28.61"),
        "stock": Decimal("50.00"),
        "unit": "set",
        "weight": "7-Piece Ritual Set",
        "brand": "Vedic Craft",
        "image": "products/puja_thali.jpg",
    },
    {
        "id": 21,
        "name": "Traditional South Silk Saree with Rich Zari Border",
        "cat_slug": "saree",
        "description": "Gorgeous festive hand-woven silk saree with contrasting royal magenta border, golden zari butta, and matching unstitched blouse piece.",
        "price": Decimal("1499.00"),
        "discount": Decimal("46.70"),
        "stock": Decimal("35.00"),
        "unit": "piece",
        "weight": "5.5m Saree + 0.8m Blouse",
        "brand": "Apna Poshak",
        "image": "products/kurti.jpg",
    },
    {
        "id": 22,
        "name": "Men Pure Cotton Chikankari Casual Kurta",
        "cat_slug": "kurta-ethnic-wear",
        "description": "Elegant breathable long cotton kurta with delicate hand embroidery and sandalwood buttons, ideal for festivals and casual wear.",
        "price": Decimal("799.00"),
        "discount": Decimal("37.55"),
        "stock": Decimal("60.00"),
        "unit": "piece",
        "weight": "Sizes: 38, 40, 42, 44",
        "brand": "Apna Poshak",
        "image": "products/mens_kurta.jpg",
    },
    {
        "id": 23,
        "name": "Heavy Gauge Stainless Steel Deep Kadhai (2.5 L)",
        "cat_slug": "steel-utensils",
        "description": "Premium induction and gas compatible triply stainless steel kadhai with stay-cool riveted loop handles for deep frying and curries.",
        "price": Decimal("899.00"),
        "discount": Decimal("27.81"),
        "stock": Decimal("45.00"),
        "unit": "piece",
        "weight": "2.5 Litre Capacity • Triply Steel",
        "brand": "Classic Steel",
        "image": "products/kadhai.jpg",
    },
    {
        "id": 24,
        "name": "VoltPro 20W Type-C Fast Charger & Braided Cable",
        "cat_slug": "chargers-cables",
        "description": "BIS certified 20W USB-C PD high-speed wall adapter with 1-metre durable fast-charging data cable for all smartphones.",
        "price": Decimal("599.00"),
        "discount": Decimal("50.08"),
        "stock": Decimal("75.00"),
        "unit": "piece",
        "weight": "20W Adapter + 1m Cable",
        "brand": "VoltPro",
        "image": "products/charger.jpg",
    },
    {
        "id": 25,
        "name": "True Wireless Stereo Earbuds with Deep Bass & Mic",
        "cat_slug": "earphones-headphones",
        "description": "Bluetooth 5.3 earbuds featuring environmental noise cancellation, rich dynamic bass, touch controls, and 32-hour battery life.",
        "price": Decimal("1499.00"),
        "discount": Decimal("46.70"),
        "stock": Decimal("65.00"),
        "unit": "piece",
        "weight": "Bluetooth 5.3 • Type-C Fast Charge",
        "brand": "AcousticPlus",
        "image": "products/earbuds.jpg",
    },
    {
        "id": 26,
        "name": "Maggi 2-Minute Masala Instant Noodles (Pack of 4)",
        "cat_slug": "biscuits-snacks",
        "description": "India's favourite instant masala noodles with goodness of iron and signature spice blend, ready in just 2 minutes!",
        "price": Decimal("60.00"),
        "discount": Decimal("6.67"),
        "stock": Decimal("150.00"),
        "unit": "pack",
        "weight": "280 g (4 x 70g Packs)",
        "brand": "Nestle Maggi",
        "image": "products/noodles.jpg",
    },
    {
        "id": 27,
        "name": "Parle-G Original Gluco Biscuits Family Pack",
        "cat_slug": "biscuits-snacks",
        "description": "The beloved tea-time companion for generations filled with wheat and milk goodness. Desh Ka Apna Biscuit!",
        "price": Decimal("75.00"),
        "discount": Decimal("9.33"),
        "stock": Decimal("200.00"),
        "unit": "pack",
        "weight": "800 g Family Pack",
        "brand": "Parle-G",
        "image": "products/biscuits.jpg",
    },
    {
        "id": 28,
        "name": "Haldiram's Nagpur Crispy Aloo Bhujia Namkeen",
        "cat_slug": "biscuits-snacks",
        "description": "Spicy and crispy potato and gram flour sev flavored with a unique blend of mint and Indian spices.",
        "price": Decimal("115.00"),
        "discount": Decimal("8.70"),
        "stock": Decimal("120.00"),
        "unit": "pack",
        "weight": "400 g Pouch",
        "brand": "Haldiram's",
        "image": "products/namkeen.jpg",
    },
    {
        "id": 29,
        "name": "Tata Tea Gold Assam CTC & Long Leaves Tea",
        "cat_slug": "tea-coffee",
        "description": "A rich blend of fine Assam CTC teas with 15% gently rolled long leaves for an irresistible aroma and full-bodied taste.",
        "price": Decimal("310.00"),
        "discount": Decimal("11.29"),
        "stock": Decimal("90.00"),
        "unit": "pack",
        "weight": "500 g Pouch",
        "brand": "Tata Tea",
        "image": "products/chai.jpg",
    },
    {
        "id": 30,
        "name": "Amul Pure Cow Ghee in Steel Container",
        "cat_slug": "ghee",
        "description": "Traditional granular cow ghee with rich golden colour and divine aroma. Made from fresh cream of pure cow milk.",
        "price": Decimal("610.00"),
        "discount": Decimal("5.74"),
        "stock": Decimal("70.00"),
        "unit": "litre",
        "weight": "1 Litre Container",
        "brand": "Amul",
        "image": "products/ghee.jpg",
    },
    {
        "id": 31,
        "name": "Fresh Red Nasik Onions / Pyaaz",
        "cat_slug": "vegetables",
        "description": "Premium farm-fresh firm and pungent red onions from Nasik fields, essential for Indian gravies, tadka and salads.",
        "price": Decimal("35.00"),
        "discount": Decimal("20.00"),
        "stock": Decimal("250.00"),
        "unit": "kg",
        "weight": "1 kg",
        "brand": "Apna Farm",
        "image": "products/onions.jpg",
    },
    {
        "id": 32,
        "name": "Fresh Farm Large Cooking Potatoes / Aloo",
        "cat_slug": "vegetables",
        "description": "High-grade starchy large potatoes, farm harvested and dry sorted. Ideal for aloo jeera, samosas and curries.",
        "price": Decimal("30.00"),
        "discount": Decimal("16.67"),
        "stock": Decimal("300.00"),
        "unit": "kg",
        "weight": "1 kg",
        "brand": "Apna Farm",
        "image": "products/potatoes.jpg",
    },
    {
        "id": 33,
        "name": "Khadi Natural Herbal Handmade Bathing Soap Bar",
        "cat_slug": "soap",
        "description": "Handcrafted Ayurvedic cleansing soap enriched with essential natural oils and lavender to keep skin soft, glowing and refreshed.",
        "price": Decimal("120.00"),
        "discount": Decimal("20.83"),
        "stock": Decimal("90.00"),
        "unit": "pack",
        "weight": "125 g Bar",
        "brand": "Khadi Natural",
        "image": "products/soap.jpg",
    },
    {
        "id": 34,
        "name": "Dabur 100% Pure Organic Multifloral Honey",
        "cat_slug": "grocery-kirana",
        "description": "Pure, unadulterated honey sourced directly from natural hives. Natural immunity booster for daily warm water or toast.",
        "price": Decimal("220.00"),
        "discount": Decimal("15.91"),
        "stock": Decimal("85.00"),
        "unit": "jar",
        "weight": "500 g Glass Jar",
        "brand": "Dabur",
        "image": "products/honey.jpg",
    },
    {
        "id": 35,
        "name": "Hawkins Contura Hard Anodized Pressure Cooker (3 Litre)",
        "cat_slug": "cookware",
        "description": "Authentic Hawkins Contura 3L pressure cooker with curved body for easy stirring, inner lid safety, and rapid cooking.",
        "price": Decimal("2100.00"),
        "discount": Decimal("21.43"),
        "stock": Decimal("40.00"),
        "unit": "piece",
        "weight": "3 Litre Inner Lid",
        "brand": "Hawkins",
        "image": "products/pressure_cooker.jpg",
    },
]

for pdata in products_data:
    pid = pdata.pop("id")
    cat_slug = pdata.pop("cat_slug")
    cat = get_cat(cat_slug)
    pdata["category"] = cat
    pdata["is_available"] = True

    prod, created = Product.objects.update_or_create(
        id=pid,
        defaults=pdata
    )
    status = "Created" if created else "Updated"
    print(f"[{status}] ID:{prod.id} | {prod.name} | MRP:Rs.{prod.price} | Sale:Rs.{prod.discounted_price} | Img:{prod.image.name}")

print("\nDatabase successfully updated with all Indian products, realistic INR prices and images!")
